### PR TITLE
Fixed lsp.lua fidget dependancy needing legacy tag and renamed 'help'…

### PR DESCRIPTION
**Pull request by deed0s**
… in treesitter to 'vimdoc'

### CODE REVIEW

**Comment by frans-johansson** [comment]
Heya! Thank you for engaging with this repository. I appreciate you taking the time to fix some of the issues you have found here 🔥 I ask that you exclude the additional plugin you included in this PR (lukas-reineke/indent-blankline.nvim), it's fine if you want to build off this repository as a sort of quick-start for your own config and add more plugins there, but I'd prefer to curate the plugins going into `main` here.

Given that you exclude the additional plugin from this PR, I'd be happy to merge it 😄

**Comment by deed0s** [comment]
> Heya! Thank you for engaging with this repository. I appreciate you taking the time to fix some of the issues you have found here 🔥 I ask that you exclude the additional plugin you included in this PR (lukas-reineke/indent-blankline.nvim), it's fine if you want to build off this repository as a sort of quick-start for your own config and add more plugins there, but I'd prefer to curate the plugins going into `main` here.
> 
> Given that you exclude the additional plugin from this PR, I'd be happy to merge it 😄

Thanks for the heads up, I didn't realise I included those in the PR, I've excluded them now so should be safw to merge

**Comment by frans-johansson** [comment]
Great stuff, I just noticed that all config files have been moved from their original locations (not sure how I missed this the first time 🙃). As per https://github.com/frans-johansson/lazy-nvim-starter/issues/1, I'd prefer to keep the current structure, seeing as it makes the repo easier to manage locally together with your other dotfiles e.g. with `stow`.

In short, the files should all be organized under ".config/nvim/...", rather than directly in the root directory.

**Comment by deed0s** [comment]
should be all good to go now, and yeah definitely more manageable the way it was originally

**Review by frans-johansson — APPROVED** [review]
Looks good to me, I'll go ahead and merge this in ASAP 🔥

**Pull request merged**
